language: node_js
node_js:
  - 10

services:
  - docker

script:
  - npm run lint || exit 1
  - docker build . -t gt-dev
  - docker run -d -p 3000:3000 gt-dev
  - sleep 30
  - curl http://localhost:3000
